import '../domain/app_models.dart';
import 'qso_repository.dart';

class ExportService {
  ExportService(this._qsoRepository);

  final QsoRepository _qsoRepository;

  Future<String> exportAdif(ExportFilter filter) async {
    final qsos = await _qsoRepository.listQsos(_queryFromFilter(filter));
    final buffer = StringBuffer()
      ..writeln('Generated by QSO Scribe')
      ..writeln('<PROGRAMID:10>QSO Scribe')
      ..writeln('<EOH>');

    for (final qso in qsos) {
      buffer.writeln(_toAdifRecord(qso));
    }
    return buffer.toString();
  }

  Future<String> exportCsv(ExportFilter filter) async {
    final qsos = await _qsoRepository.listQsos(_queryFromFilter(filter));
    final buffer = StringBuffer()
      ..writeln(
        [
          'Callsign',
          'DateTime',
          'Band',
          'Frequency',
          'Mode',
          'SentRST',
          'ReceivedRST',
          'Name',
          'QTH',
          'Notes',
          'Rig',
          'Antenna',
          'Status',
        ].join(','),
      );

    for (final qso in qsos) {
      buffer.writeln(
        [
          qso.callsign.value,
          qso.dateTime.value?.toUtc().toIso8601String() ?? '',
          qso.band.value,
          qso.frequency.value,
          qso.mode.value,
          qso.sentRst.value,
          qso.receivedRst.value,
          qso.name?.value ?? '',
          qso.qth?.value ?? '',
          qso.notes?.value ?? '',
          qso.rig?.value ?? '',
          qso.antenna?.value ?? '',
          qso.status.name,
        ].map(_csvCell).join(','),
      );
    }

    return buffer.toString();
  }

  Future<String> exportRawTranscript(ExportFilter filter) async {
    final qsos = await _qsoRepository.listQsos(_queryFromFilter(filter));
    final buffer = StringBuffer();
    for (final qso in qsos) {
      buffer
        ..writeln('## ${qso.callsign.value}')
        ..writeln('Status: ${qso.status.name}')
        ..writeln('Date: ${qso.dateTime.value?.toIso8601String() ?? ''}')
        ..writeln(qso.rawTranscript ?? '')
        ..writeln();
    }
    return buffer.toString();
  }

  QsoQuery _queryFromFilter(ExportFilter filter) {
    return QsoQuery(
      status: filter.status,
      from: filter.from,
      to: filter.to,
      band: filter.band,
      mode: filter.mode,
    );
  }

  String _toAdifRecord(QsoDraft qso) {
    final dateTime = qso.dateTime.value;
    return [
      _adifField('CALL', qso.callsign.value),
      if (dateTime != null) _adifField('QSO_DATE', _adifDate(dateTime)),
      if (dateTime != null) _adifField('TIME_ON', _adifTime(dateTime)),
      _adifField('BAND', qso.band.value),
      _adifField('FREQ', qso.frequency.value),
      _adifField('MODE', qso.mode.value),
      _adifField('RST_SENT', qso.sentRst.value),
      _adifField('RST_RCVD', qso.receivedRst.value),
      if (qso.name?.value.isNotEmpty ?? false)
        _adifField('NAME', qso.name!.value),
      if (qso.qth?.value.isNotEmpty ?? false) _adifField('QTH', qso.qth!.value),
      if (qso.notes?.value.isNotEmpty ?? false)
        _adifField('COMMENT', qso.notes!.value),
      if (qso.rig?.value.isNotEmpty ?? false)
        _adifField('MY_RIG', qso.rig!.value),
      '<EOR>',
    ].join(' ');
  }

  String _adifField(String name, String value) =>
      '<$name:${value.length}>$value';

  String _adifDate(DateTime value) {
    final utc = value.toUtc();
    return '${utc.year.toString().padLeft(4, '0')}'
        '${utc.month.toString().padLeft(2, '0')}'
        '${utc.day.toString().padLeft(2, '0')}';
  }

  String _adifTime(DateTime value) {
    final utc = value.toUtc();
    return '${utc.hour.toString().padLeft(2, '0')}'
        '${utc.minute.toString().padLeft(2, '0')}'
        '${utc.second.toString().padLeft(2, '0')}';
  }

  String _csvCell(String value) {
    final escaped = value.replaceAll('"', '""');
    return '"$escaped"';
  }
}
